### ISSUE TITLE
documentation simulation_1000GP_Phase3_chr1/phenotype/ is missing

### ISSUE THREAD

**Issue by lainmn** [eldronzhou/SDPRX_paper#1]
Hi! I notice that in the simulation part, specifically in the R code "getRes.R" there is a path "simulation_1000GP_Phase3_chr1/phenotype/" that is totally missing from the files you provided on google drive. I guess you did not upload the part related to phenotype.

**Comment by eldronzhou** [comment]
Hi! Thank you for bringing this issue to my attention. I have uploaded the phenotype data to the google drive. Other files like genotype and effect sizes are also updated due to the change made in the revision.
